# This file was generated by GoReleaser. DO NOT EDIT.
cask "kure" do
  name "kure"
  desc "Cross-platform CLI password manager with sessions"
  homepage "https://github.com/GGP1/kure"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kure"

  on_macos do
    on_intel do
      url "https://github.com/GGP1/kure/releases/download/v#{version}/kure_v#{version}_darwin_amd64.tar.gz"
      sha256 "538c32f3915a2556e5eaed8b8e04a0bd7e289e5903035a8498762dcba16e36da"
    end
    on_arm do
      url "https://github.com/GGP1/kure/releases/download/v#{version}/kure_v#{version}_darwin_arm64.tar.gz"
      sha256 "2376d5b73661775f3b53614a7a991305d3365f34e3df6eaff562817643ecfb63"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GGP1/kure/releases/download/v#{version}/kure_v#{version}_linux_amd64.tar.gz"
      sha256 "c7906591fba46f4b85fc0fabac1ea09c30c3f26d0641147c29f73a9e22733f87"
    end
    on_arm do
      url "https://github.com/GGP1/kure/releases/download/v#{version}/kure_v#{version}_linux_arm64.tar.gz"
      sha256 "c01aeb79c243129e9d82db782d0710a4968833e401ba2147ce9ee85d64cb282e"
    end
  end

  # No zap stanza required
end
