# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Comeet < Formula
  desc "Service that keeps track of events from multiple calendar services and accounts, and sends you notifications."
  homepage "https://github.com/GGP1/comeet"
  version "0.1.0"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/GGP1/comeet/releases/download/v0.1.0/comeet_v0.1.0_macOS_64bit.tar.gz"
    sha256 "0386e898772ac8620cc71d4cc060344e5a49f97ded3ab7abbd6eca5ad09c09b5"

    def install
      bin.install "comeet"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Comeet
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GGP1/comeet/releases/download/v0.1.0/comeet_v0.1.0_Linux_ARMv6.tar.gz"
      sha256 "8e45e20292dd766df133747720bd27943afac1af3664139322b0d1381b5451b2"

      def install
        bin.install "comeet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GGP1/comeet/releases/download/v0.1.0/comeet_v0.1.0_Linux_64bit.tar.gz"
      sha256 "5d766c01f50ddd389c8a680885d06e93ef346b63ad639e1fc53f9a4227104392"

      def install
        bin.install "comeet"
      end
    end
  end
end
