# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kure < Formula
  desc "Cross-platform CLI password manager with sessions"
  homepage "https://github.com/GGP1/kure"
  version "0.8.3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GGP1/kure/releases/download/v0.8.3/kure_v0.8.3_darwin_amd64.tar.gz"
      sha256 "ef49eef57c232f0fd8f8ac5189f4779a9e5ec14bc7c91830fac531213e3ecaff"

      def install
        bin.install "kure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GGP1/kure/releases/download/v0.8.3/kure_v0.8.3_darwin_arm64.tar.gz"
      sha256 "fb5c795f7e8067949a9cbd6ecf140890c61b15fc2b1e1c8e722ff3af914b937d"

      def install
        bin.install "kure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GGP1/kure/releases/download/v0.8.3/kure_v0.8.3_linux_arm64.tar.gz"
      sha256 "f028cb9609740556b38ca433363fcadd587ad7ef777768e5352de554792984ed"

      def install
        bin.install "kure"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GGP1/kure/releases/download/v0.8.3/kure_v0.8.3_linux_amd64.tar.gz"
      sha256 "daa08d5ea65932474dcb4b6a409fa2baea92c176f7bcff2b678233c3e0a351ee"

      def install
        bin.install "kure"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GGP1/kure/releases/download/v0.8.3/kure_v0.8.3_linux_armv6.tar.gz"
      sha256 "48fdaa4091b63a501a4b849417f1eea398cb2cd1a6b78600756859ceace30e83"

      def install
        bin.install "kure"
      end
    end
  end
end
