# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kure < Formula
  desc "Cross-platform CLI password manager with sessions"
  homepage "https://github.com/GGP1/kure"
  version "1.0.0"
  license "Apache 2.0"

  on_macos do
    on_intel do
      url "https://github.com/GGP1/kure/releases/download/v1.0.0/kure_v1.0.0_darwin_amd64.tar.gz"
      sha256 "9530174bd0d23915deaee45c2dd28876db176c1fba89b23f966161b147ef32c8"

      def install
        bin.install "kure"
      end
    end
    on_arm do
      url "https://github.com/GGP1/kure/releases/download/v1.0.0/kure_v1.0.0_darwin_arm64.tar.gz"
      sha256 "dcfa4de0497228e8b8268ca1b873106e39eb6f2f0268a9c4d00cd2e07fbc81b8"

      def install
        bin.install "kure"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GGP1/kure/releases/download/v1.0.0/kure_v1.0.0_linux_amd64.tar.gz"
        sha256 "b84c0a72b3ee62363e327e3628463a61494a5301f5ad4ac4ba009c25184d0c22"

        def install
          bin.install "kure"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/GGP1/kure/releases/download/v1.0.0/kure_v1.0.0_linux_armv6.tar.gz"
        sha256 "ba46f19f8e053918e473d36647867d473107d002f860be396c51047543a40c3c"

        def install
          bin.install "kure"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GGP1/kure/releases/download/v1.0.0/kure_v1.0.0_linux_arm64.tar.gz"
        sha256 "7f51bdbe03505a19a7f850603e1f1699a8f1c4cea345b874ab9c6e67c2b04733"

        def install
          bin.install "kure"
        end
      end
    end
  end
end
